In [5]:
import pandas as pd

In [17]:
df_customer = pd.read_parquet('./training_data/consumer_data.parquet')  # pandas will auto-detect the engine
# print(df_customer.head())
df_customer.head()

  evaluation_date  FPF_TARGET  total_balance masked_consumer_id
0      2021-08-26         0.0        1380.84          C01100001
1      2022-08-02         0.0       20163.90          C01100002
2      2021-03-04         0.0        3986.25          C01100003
3      2022-11-19         0.0        5956.03          C01100004
4      2021-11-21         0.0       29421.10          C01100005

In [18]:
df_customer['FPF_TARGET'].value_counts()

FPF_TARGET
0.0    13530
1.0     2470
Name: count, dtype: int64

In [20]:
df_customer[df_customer['FPF_TARGET'] == 1].head(10)

     evaluation_date  FPF_TARGET  total_balance masked_consumer_id
174       2022-03-31         1.0       39534.66          C01100175
175       2021-08-03         1.0       33788.73          C01100176
417       2022-04-23         1.0        9472.89          C01100418
479       2021-11-29         1.0        1704.32          C01100480
783       2022-05-03         1.0        9773.72          C01100784
820       2023-03-16         1.0        -959.84          C01100821
901       2022-05-20         1.0         953.77          C01100902
1003      2022-11-03         1.0       60444.94          C01101004
1127      2023-02-03         1.0        6375.33          C01101128
1168      2023-03-03         1.0       15694.34          C01101169

In [23]:
df_customer['masked_consumer_id'].unique()

array(['C01100001', 'C01100002', 'C01100003', ..., 'C04104998',
       'C04104999', 'C04105000'], dtype=object)

In [7]:
df_customer.describe()

         FPF_TARGET  total_balance
count  16000.000000   1.599900e+04
mean       0.154375   6.524654e+03
std        0.361319   3.557948e+04
min        0.000000  -1.153690e+04
25%        0.000000   9.923000e+01
50%        0.000000   7.810900e+02
75%        0.000000   3.539625e+03
max        1.000000   2.371577e+06

In [8]:
df_transaction = pd.read_parquet('./training_data/transactions.parquet')
print(df_transaction.head())
df_transaction.describe()

        masked_consumer_id posted_date  amount  category masked_transaction_id
2715977          C02103629  2022-08-12  -21.00      27.0          C02T02715977
2715978          C02103629  2022-08-09   -8.60      22.0          C02T02715978
2715979          C02103629  2022-08-07  -30.05      16.0          C02T02715979
2715980          C02103629  2022-09-29   -0.46       0.0          C02T02715980
2715981          C02103629  2022-07-21  -50.00      12.0          C02T02715981

             amount      category
count  1.773796e+07  1.773796e+07
mean  -7.262228e-01  1.259718e+01
std    2.992456e+03  7.710338e+00
min   -2.088929e+06  0.000000e+00
25%   -5.163000e+01  4.000000e+00
50%   -1.775000e+01  1.500000e+01
75%   -3.730000e+00  1.700000e+01
max    2.088929e+06  3.600000e+01

In [9]:
df_transaction.count()

masked_consumer_id       17738083
posted_date              17737962
amount                   17737962
category                 17737962
masked_transaction_id    17738083
dtype: int64

In [10]:
df_transaction.value_counts()

masked_consumer_id  posted_date  amount    category  masked_transaction_id
C01100001           2020-08-27   -199.36   26.0      C01T0648                 1
C03104400           2022-11-14    20.00    1.0       C03T05451174             1
                                 -10.00    16.0      C03T05451944             1
                                 -9.50     16.0      C03T05451945             1
                                 -8.86     18.0      C03T05451943             1
                                                                             ..
C02102417           2022-12-31    25.00    10.0      C02T01798697             1
                    2023-01-01   -25.00    16.0      C02T01799248             1
                                 -11.25    16.0      C02T01799543             1
                                  2.82     1.0       C02T01798758             1
C04105000           2023-03-31    2350.00  2.0       C04T06613691             1
Name: count, Length: 17737962, dtype: int64

In [33]:
df_transaction['masked_transaction_id'].nunique()

17738083

In [32]:
df_transaction[df_transaction.columns].nunique()

masked_consumer_id          16000
posted_date                  1985
amount                     400687
category                       37
masked_transaction_id    17738083
dtype: int64

In [11]:
df_transaction.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17738083 entries, 2715977 to 1072784
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   masked_consumer_id     object
 1   posted_date            object
 2   amount                 float64
 3   category               float64
 4   masked_transaction_id  object
dtypes: float64(2), object(3)
memory usage: 812.0+ MB

In [12]:
from mlc.cashflow import ScorableModelTemplate, compute_score
import numpy as np
import pandas as pd

class ScorableModel(ScorableModelTemplate):

    # def predict(self, raw_files: list[str]):
    #     """Input argument will vary. See you competition's template.

    #     :param raw_files: list of file path strings, depends on competition
    #     :return predictions: dataframe or np.array, depends on competition
    #     """
    #     # Implement this: may return random predictions for the first assignment
    #     # raise NotImplementedError()
    def predict(self, raw_consumer_file: str, raw_transactions_file: str):
        """Predict labels and positions of bugs.

        :param raw_consumer_file: path to consumer_data.parquet
        :param raw_consumer_file: path to transactions.parquet
        """
        # raise NotImplementedError()
        # raw_consumer_file = '../cashflow/consumer_data.parquet'
        # raw_transactions_file = '../cashflow/transactions.parquet'
        df_consumer = self.process_inputs(raw_consumer_file, raw_transactions_file)
        # X_train = df_consumer.drop(columns=['evaluation_date', 'FPF_TARGET'])
        # y_train = df_consumer['FPF_TARGET']
        # model = XGBClassifier()
        # model.fit(X_train, y_train)
        # probs = model.predict_proba(X_test)[:, 1]
        probs = np.random.choice(2, len(df_consumer))  # Placeholder for actual model predictions
        # probs = round(probs)
        return probs


    # def process_inputs(self, raw_files: list[str]):
    #     """Input argument will vary. See you competition's template.

    #     :param raw_files: list of file path strings, depends on competition
    #     :return: anything needed for you model to make predictions, e.g. features or processed data
    #     """
    #     # Implement this: only need to read in files for first assignment
    #     # raise NotImplementedError()
    def process_inputs(self, raw_consumer_file: str, raw_transactions_file: str):
        """Read in arrays and compute features.

        :param raw_files: path to transactions.parquet
        :return: anything needed for you model to make predictions, e.g. features or processed data
        """
        # raise NotImplementedError()
        df_consumer = pd.read_parquet(raw_consumer_file)
        df_transactions = pd.read_parquet(raw_transactions_file)
        df_consumer['num_transactions'] = df_transactions.groupby('masked_consumer_id')['masked_transaction_id'].transform('count')
        df_consumer['total_amount'] = df_transactions.groupby('masked_consumer_id')['amount'].transform('sum')
        return df_consumer

# Intialize, runs: __check_rep__ to validate class
model = ScorableModel() # error will be raised if the above is not implemented correctly
# model.__check_rep__()
# print(compute_score())
from pathlib import Path
# DATA = Path(__file__).resolve().parent / "test_data"
# DATA = "/mlc/cashflow/test_data/"
_, true_output = model.load_test_case()
predicted_output = model.predict("mlc/test_data/consumer_data.parquet", "mlc/test_data/transactions.parquet")

In [13]:
score = compute_score(true_output, predicted_output)
print(score)

0.5

In [14]:
true_output

,evaluation_date,FPF_TARGET,total_balance,masked_consumer_id,group_id,y_pred
0,2021-08-26,0.0,1380.84,C01100001,C01,0
174,2022-03-31,1.0,39534.66,C01100175,C01,0

In [15]:
predicted_output

array([0, 0])

In [16]:
df_test_trans = pd.read_parquet("mlc/test_data/transactions.parquet")
df_test_trans

       masked_consumer_id posted_date   amount  category masked_transaction_id
0               C01100001  2021-06-29   926.89       4.0                C01T00
1               C01100001  2020-11-16   300.00       0.0                C01T01
2               C01100001  2020-11-25   500.00       0.0                C01T02
3               C01100001  2020-09-03  1000.00       0.0                C01T03
4               C01100001  2020-11-09   200.00       0.0                C01T04
...                   ...         ...      ...       ...                   ...
187433          C01100175  2022-01-25  -570.50      15.0           C01T0187433
187434          C01100175  2021-12-06   -13.02      14.0           C01T0187434
187435          C01100175  2021-04-26   -39.40      18.0           C01T0187435
187436          C01100175  2022-01-28   -39.90      14.0           C01T0187436
187437          C01100175  2021-10-04 -7500.00      15.0           C01T0187437

[2928 rows x 5 columns]

In [42]:
df1 = df_transaction.groupby('masked_consumer_id')['amount'].sum()
df_customer['tt'] = df1.values
df_customer
# df1.values

,evaluation_date,FPF_TARGET,total_balance,masked_consumer_id,total_amount,tt
0,2021-08-26,0.0,1380.84,C01100001,-8111.42,-8111.42
1,2022-08-02,0.0,20163.90,C01100002,-9490.73,-9490.73
2,2021-03-04,0.0,3986.25,C01100003,2137.77,2137.77
3,2022-11-19,0.0,5956.03,C01100004,-29837.87,-29837.87
4,2021-11-21,0.0,29421.10,C01100005,-9756.37,-9756.37
...,...,...,...,...,...,...
4995,2023-03-31,0.0,1412.80,C04104996,-6255.18,-6255.18
4996,2023-03-31,0.0,-439.21,C04104997,1879.50,1879.50
4997,2023-03-31,0.0,84.53,C04104998,1580.63,1580.63
4998,2023-03-31,0.0,52655.88,C04104999,-18887.56,-18887.56
4999,2023-03-31,0.0,40004.69,C04105000,-123441.14,-123441.14

In [38]:
# df_customer['num_transactions'] = df_transaction.groupby('masked_consumer_id')['masked_transaction_id'].transform('count')
# df_customer['total_amount'] = df_transaction.groupby('masked_consumer_id')['amount'].sum()
# df_customer
# First compute total amount per customer
total_amount_per_customer = df_transaction.groupby('masked_consumer_id')['amount'].sum()

# Then map that to df_customer
df_customer['total_amount'] = df_customer['masked_consumer_id'].map(total_amount_per_customer)
df_customer

,evaluation_date,FPF_TARGET,total_balance,masked_consumer_id,total_amount
0,2021-08-26,0.0,1380.84,C01100001,-8111.42
1,2022-08-02,0.0,20163.90,C01100002,-9490.73
2,2021-03-04,0.0,3986.25,C01100003,2137.77
3,2022-11-19,0.0,5956.03,C01100004,-29837.87
4,2021-11-21,0.0,29421.10,C01100005,-9756.37
...,...,...,...,...,...
4995,2023-03-31,0.0,1412.80,C04104996,-6255.18
4996,2023-03-31,0.0,-439.21,C04104997,1879.50
4997,2023-03-31,0.0,84.53,C04104998,1580.63
4998,2023-03-31,0.0,52655.88,C04104999,-18887.56
4999,2023-03-31,0.0,40004.69,C04105000,-123441.14

In [31]:
df_transaction.groupby('masked_consumer_id')['amount'].sum()

masked_consumer_id
C01100001     -8111.42
C01100002     -9490.73
C01100003      2137.77
C01100004    -29837.87
C01100005     -9756.37
               ...
C04104996     -6255.18
C04104997      1879.50
C04104998      1580.63
C04104999    -18887.56
C04105000   -123441.14
Name: amount, Length: 16000, dtype: float64